<div class="nav-bar">
    <!-- menu start -->
    <?php echo $this->getMenuLevel($this->getMenuArray()); ?>
    <!-- menu end -->

    <?php echo $this->getChildHtml('config_search', true, true); ?>

    <a id="page-help-link" href="<?php echo Mage::helper('adminhtml')->getPageHelpUrl() ?>"><?php echo $this->__('Get help for this page') ?></a>
    <script type="text/javascript">$('page-help-link').target = 'magento_page_help'</script>

</div>
