<?php /** @var Oggetto_AdminConfigSearch_Block_Adminhtml_Search $this */ ?>
<script>
    ConfigSingleton.setConfigArray(<?php echo "'" . $this->getConfigArray() . "'"; ?>);
</script>
<form id="config-fields-search" class="config-search-form" action="#" method="GET"
      data-url-switch="<?php echo $this->getUrlForFieldValueSwitch(); ?>">
    <input type="text" id="search-settings" class="autocomplete-input" autocomplete="off" placeholder="config search"><br>
</form>